# Generated by Django 5.2.3 on 2026-03-24 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userstats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserStats',
        ),
    ]
