# Generated by Django 5.2.3 on 2026-03-30 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='equipped_avatar_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_avatar_by', to='gamification.storeitem'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='equipped_sound_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_sound_by', to='gamification.storeitem'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='equipped_theme_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_theme_by', to='gamification.storeitem'),
        ),
    ]
