# Generated by Django 5.2.3 on 2026-03-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_userprofile_equipped_avatar_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_focus_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
