# Generated by Django 5.2.3 on 2026-03-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_userprofile_total_focus_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='daily_goal_minutes',
            field=models.IntegerField(default=120),
        ),
    ]
