# Generated by Django 5.2.3 on 2026-03-31 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reward_granted',
            field=models.BooleanField(default=False),
        ),
    ]
