# Generated by Django 5.2.3 on 2026-03-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_category_task_pomodoro_done_task_pomodoro_total_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='pomodoro_done',
            new_name='pomodoro_completed',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='pomodoro_total',
            new_name='pomodoro_estimated',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasksubtask',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
