# Generated by Django 5.2.3 on 2026-03-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='focus_minutes_completed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
