# Generated by Django 5.2.3 on 2026-03-24 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_focus_minutes_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='pomodoro_estimated',
        ),
    ]
