# Generated by Django 5.2.3 on 2026-03-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_task_pomodoro_estimated'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='pomodoro_estimated',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
