# Generated by Django 5.2.3 on 2026-03-24 17:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0002_pomodorosession_pomodorosettings_userstats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstats',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='pomodorosession',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='pomodorosession',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='pomodorosession',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='pomodorosession',
            name='started_at',
        ),
        migrations.AddField(
            model_name='pomodorosession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pomodorosession',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='pomodorosession',
            name='type',
            field=models.CharField(choices=[('focus', 'Foco')], default='focus', max_length=20),
        ),
        migrations.AlterField(
            model_name='pomodorosession',
            name='completed',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='PomodoroSettings',
        ),
        migrations.DeleteModel(
            name='UserStats',
        ),
    ]
