# Generated by Django 5.2.3 on 2026-03-26 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0003_remove_userstats_user_alter_pomodorosession_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pomodorosession',
            options={'ordering': ['-started_at']},
        ),
        migrations.RenameField(
            model_name='pomodorosession',
            old_name='duration_minutes',
            new_name='planned_minutes',
        ),
        migrations.RenameField(
            model_name='pomodorosession',
            old_name='created_at',
            new_name='started_at',
        ),
        migrations.RemoveField(
            model_name='pomodorosession',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='pomodorosession',
            name='date',
        ),
        migrations.RemoveField(
            model_name='pomodorosession',
            name='type',
        ),
        migrations.AddField(
            model_name='pomodorosession',
            name='earned_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pomodorosession',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pomodorosession',
            name='session_type',
            field=models.CharField(choices=[('focus', 'Focus'), ('short_break', 'Short Break'), ('long_break', 'Long Break')], default='focus', max_length=20),
        ),
        migrations.AddField(
            model_name='pomodorosession',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], default='running', max_length=20),
        ),
        migrations.CreateModel(
            name='PomodoroSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_minutes', models.PositiveIntegerField(default=25)),
                ('short_break_minutes', models.PositiveIntegerField(default=5)),
                ('long_break_minutes', models.PositiveIntegerField(default=15)),
                ('cycles_before_long_break', models.PositiveIntegerField(default=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pomodoro_setting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
