# Generated by Django 5.2.3 on 2026-04-02 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('task_overdue', 'Tarefa atrasada'), ('task_due_today', 'Tarefa vence hoje'), ('daily_goal_completed', 'Meta diária concluída'), ('chest_ready', 'Baú disponível'), ('focus_coins_ready', 'Minutos prontos para conversão'), ('level_up', 'Subida de nível'), ('streak_warning', 'Sequência em risco'), ('no_focus_today', 'Sem foco hoje'), ('good_progress_today', 'Bom progresso diário'), ('streak_congrats', 'Sequência mantida'), ('task_completed', 'Tarefa concluída')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta')], default='low', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('unique_key', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('unique_key__isnull', False)), fields=('user', 'unique_key'), name='unique_notification_per_user_key')],
            },
        ),
    ]
