# Generated by Django 5.2.3 on 2026-03-28 06:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('xp_reward', models.IntegerField()),
                ('coin_reward', models.IntegerField(default=0)),
                ('target_value', models.IntegerField()),
                ('current_value', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('avatar', 'Avatar'), ('theme', 'Tema'), ('sound', 'Som')], max_length=20)),
                ('rarity', models.CharField(choices=[('Comum', 'Comum'), ('Raro', 'Raro'), ('Épico', 'Épico'), ('Lendário', 'Lendário')], default='Comum', max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('visual_resource', models.CharField(help_text='Emoji ou nome do ícone', max_length=100)),
                ('required_level', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('current_xp', models.IntegerField(default=0)),
                ('xp_to_next_level', models.IntegerField(default=100)),
                ('coins', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('pending_focus_minutes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('streak', models.IntegerField(default=0)),
                ('total_pomodoros', models.IntegerField(default=0)),
                ('total_tasks_completed', models.IntegerField(default=0)),
                ('last_activity', models.DateField(auto_now=True)),
                ('daily_goal_progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('wood_chest_claimed', models.BooleanField(default=False)),
                ('silver_chest_claimed', models.BooleanField(default=False)),
                ('gold_chest_claimed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_equipped', models.BooleanField(default=False)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.storeitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'item')},
            },
        ),
    ]
