# Generated by Django 5.2.3 on 2026-03-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_userprofile_daily_goal_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='today_focus_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
